// Peticiones Beer
### Funciona
GET http://localhost:8080/beers






### No funciona
POST http://localhost:8080/beer

Content-Type: application/json
{

    "breweryId": 1,
    "name": "Ale del Bosque",
    "categoryId": 1,
    "styleId": 1,
    "abv": 5.0,
    "ibu": 30.0,
    "srm": 15.0,
    "upc": 123456789,
    "filepath": "",
    "descript": "Una cerveza de tipo ale inspirada en los bosques, con aromas a hierbas frescas y un sabor equilibrado.",
    "add_user": 1,
    "last_mod": "2023-10-30T12:00:00.000+00:00"

}




### Funciona (hay que cambiar el id y el nombre a buscar según los datos de beers.sql)
GET http://localhost:8080/beer/2




### Funciona (se le pasa el id de la cerveza que queremos eliminar)
DELETE http://localhost:8080/beer/9




###
PUT http://localhost:8080/beer/4

Content-Type: application/json
{
  "breweryId": 1,
    "name": "Golden Ale",
    "categoryId": 2,
    "styleId": 3,
    "abv": 9.5,
    "ibu": 20.0,
    "srm": 6.0,
    "upc": 0,
    "filepath": "",
    "descript": "",
    "add_user": 0,
    "last_mod": "2023-10-30T12:00:00.000+00:00"
}




// Peticiones Brewery

### Funciona
GET http://localhost:8080/breweries




### No funciona (hay que cambiar el id y el nombre a buscar según los datos de breweries.sql)
GET http://localhost:8080/brewery/4





// Peticiones Category

### Funciona
GET http://localhost:8080/categories





### Funciona (hay que cambiar el id y el nombre a buscar según los datos de categories.sql)
GET http://localhost:8080/category/6




// Peticiones Style

### No funciona
GET http://localhost:8080/styles





### No funciona (hay que cambiar el id y el nombre a buscar según los datos de styles.sql)
GET http://localhost:8080/style/4




