spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebaspringboot
    username: root
    password: Mariposa$$100
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
